### ISSUE TITLE
Simple mode parser: custom types wrapped in an unnecessary array

### ISSUE THREAD

**Issue by Janiczek** [kraklin/elm-debug-transformer#3]
Trying to parse `msg: MyList [1,2]` with the simple mode parser results in:
```js
{ "MyList": [ [ 1, 2 ] ] }
```
I'd expect it to return
```js
{ "MyList": [ 1, 2 ] }
```
Unfortunately this is the first time I see PEG parsers, so I don't have an idea what in the custom types definition is wrong :disappointed: 
```
CustomType 
  = mainType:Type values:(_ value:Value {return value;})+ {return {[mainType]: values};}
  / mainType:Type _ "(" _ customType:CustomType _ ")" {return {[mainType]: customType};}
```

**Comment by Janiczek** [comment]
I have tried tinkering around at https://pegjs.org/online and have removed the `+` in the second line, and that seems to do the trick. I'm not sure it doesn't break something else though. So just throwing that out there :upside_down_face:

**Comment by kraklin** [comment]
Thank you for the issue. The array in the simple mode is there because you can have multiple type values, say:
```
User Int String (List Int)
``` 
then I had to map it to tha array so it is browsable with the object browser.

I already have this simplification in the upcoming release 

https://github.com/kraklin/elm-debug-transformer/blob/ts_rewrite/src/formatters/SimpleFormatter.ts#L18

**Comment by Janiczek** [comment]
Ah, makes sense, the `multiple arguments of a constructor` example didn't occur to me. :+1:
